version: 2.1

executors:
  docker_builder:
    machine:
      resource_class: large

parameters:
  artifactory_url:
    type: string
    default: https://smarsh.jfrog.io/artifactory

jobs:
  circleci_ip_ranges: true
  build-and-push-docker-image:
    executor: docker_builder
    working_directory: /tmp/build
    steps:
      - checkout
      - run:
          name: Set Placeholder Version number
          command: |
            echo "export VERSION=1.0.3" >> $BASH_ENV
      - run:
          name: Install endorctl
          command: |
            curl -sSfL https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o endorctl
            echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c
            chmod +x endorctl
            sudo mv endorctl /usr/local/bin/endorctl
            endorctl --version
      - run:
          name: Scan Source Code
          command: |
            source $BASH_ENV
            endorctl scan -p /tmp/build --api-key $ENDOR_API_KEY --api-secret $ENDOR_API_SECRET -n smarsh.fabric.one_smarsh_platform
      - run:
          name: Build Docker Image
          command: |
            docker build -t hello-world /tmp/build
      - run:
          name: Scan Docker Image
          command: |
            source $BASH_ENV
            endorctl scan -p /tmp/build --api-key $ENDOR_API_KEY --api-secret $ENDOR_API_SECRET -n smarsh.fabric.one_smarsh_platform --container hello-world
      - run:
          name: Tag Docker Image
          command: |
            docker tag hello-world smarsh-docker-snapshot-local.jfrog.io/hello-world:hello-world-$VERSION-$CIRCLE_BUILD_NUM
      - run:
          name: Log Into Docker
          command: |
            docker login -u $ARTIFACTORY_PUSH_USER -p $ARTIFACTORY_PUSH_PASS smarsh-docker-snapshot-local.jfrog.io
      - run:
          name: Push Image To Artifactory
          command: |
            docker push smarsh-docker-snapshot-local.jfrog.io/hello-world:hello-world-$VERSION-$CIRCLE_BUILD_NUM


workflows:
  build-and-push-docker-image:
    jobs:
      - build-and-push-docker-image:
          context:
            - on-prem-runtime
          filters:
            branches:
              only:
                - master
