version: 2.1

executors:
  docker_builder:
    machine:
      resource_class: medium
      image: cimg/base:2024.10

parameters:
  artifactory_url:
    type: string
    default: https://smarsh.jfrog.io/artifactory
  package_release_repo:
    type: string
    default: yum-webarch-local.jfrog.io

jobs:
  build-and-push-docker-image:
    executor: docker_builder
    working_directory: /tmp/build
    steps:
      - checkout
      - run:
          name: Set Placeholder Version number
          command: |
            echo "export VERSION=$(git rev-parse --short HEAD)" >> $BASH_ENV
      - run:
          name: Build Docker Image
          command: |
            docker build -t hello-world /tmp/build
      - run:
          name: Tag Docker Image
          command: |
            docker tag hello-world smarsh-docker-snapshot-local.jfrog.io/hello-world:hello-world-$VERSION-$CIRCLE_BUILD_NUM
      - run:
          name: Log Into Docker
          command: |
            docker login -u $ARTIFACTORY_PUSH_USER -p $ARTIFACTORY_PUSH_PASS smarsh-docker-snapshot-local.jfrog.io
      - run:
          name: Push Image To Artifactory
          command: |
            docker push smarsh-docker-snapshot-local.jfrog.io/hello-world:hello-world-$VERSION-$CIRCLE_BUILD_NUM


workflows:
  build-and-push-docker-image:
    jobs:
      - build-and-push-docker-image:
          context:
            - org-global
          filters:
            branches:
              only:
                - master
